"""add_page_visits

Revision ID: 7c4406a289f4
Revises: b8e5c1a2d3f4
Create Date: 2026-07-24 11:31:37.032692+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4406a289f4'
down_revision: str | None = 'b8e5c1a2d3f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visits',
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_returning', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_visits'))
    )
    op.create_index('ix_page_visits_created_at', 'page_visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_visits_path'), 'page_visits', ['path'], unique=False)
    op.create_index(op.f('ix_page_visits_session_id'), 'page_visits', ['session_id'], unique=False)
    op.create_index(op.f('ix_page_visits_visitor_id'), 'page_visits', ['visitor_id'], unique=False)
    op.alter_column('blog_posts', 'content',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('blog_posts', 'content',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_index(op.f('ix_page_visits_visitor_id'), table_name='page_visits')
    op.drop_index(op.f('ix_page_visits_session_id'), table_name='page_visits')
    op.drop_index(op.f('ix_page_visits_path'), table_name='page_visits')
    op.drop_index('ix_page_visits_created_at', table_name='page_visits')
    op.drop_table('page_visits')
    # ### end Alembic commands ###
