"""add_analytics_to_jobs

Revision ID: 90e55d623625
Revises: 7c4406a289f4
Create Date: 2026-07-24 13:00:37.997835+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e55d623625'
down_revision: str | None = '7c4406a289f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('visitor_id', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('device', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('browser', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('os', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('source', sa.String(length=64), nullable=True))
    op.add_column('processing_jobs', sa.Column('is_returning', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_processing_jobs_browser'), 'processing_jobs', ['browser'], unique=False)
    op.create_index(op.f('ix_processing_jobs_country'), 'processing_jobs', ['country'], unique=False)
    op.create_index(op.f('ix_processing_jobs_device'), 'processing_jobs', ['device'], unique=False)
    op.create_index(op.f('ix_processing_jobs_os'), 'processing_jobs', ['os'], unique=False)
    op.create_index(op.f('ix_processing_jobs_session_id'), 'processing_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_source'), 'processing_jobs', ['source'], unique=False)
    op.create_index(op.f('ix_processing_jobs_visitor_id'), 'processing_jobs', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_visitor_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_source'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_session_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_os'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_device'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_country'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_browser'), table_name='processing_jobs')
    op.drop_column('processing_jobs', 'is_returning')
    op.drop_column('processing_jobs', 'source')
    op.drop_column('processing_jobs', 'country')
    op.drop_column('processing_jobs', 'os')
    op.drop_column('processing_jobs', 'browser')
    op.drop_column('processing_jobs', 'device')
    op.drop_column('processing_jobs', 'session_id')
    op.drop_column('processing_jobs', 'visitor_id')
    # ### end Alembic commands ###
